
title: "YASP!"
description: "The site provide projects on data analysis, applied statistics and data science by  `Aleksandr Y. Suvorov`, [ORCID](https://orcid.org/0000-0002-2224-0019)"

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
