
title: "YASP!"
# description: A dedicated site about applied statistics, design of experiments and data science

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

css: style.min.css
